version: "3"
services:
  app:
    networks:
      - app
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: app
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "2345:2345"
      - "3000:3000"
    volumes:
      - "../:/app"

networks:
  app:
